import pubg from "@/images/PUBG.jpg"
import pubgTwo from "@/images/PUBG_2.jpg"
import pubgThree from "@/images/PUBG_3.jpg"
import fortnite from "@/images/fortnite.jpg"

export const tournamentsList = [
    {
      id: 1,
      name: "PUBG Tournament",
      game: "Counter Strike",
      type: "Elimination",
      price: "N500,000",
      status: "In Progress",
      position: "-",
      date: "1st - 21st Oct. 2024",
      src: pubg,
    },
    {
      id: 2,
      name: "FIFA 2024 Championship",
      game: "FIFA 2024",
      type: "Knockout",
      price: "N1,000,000",
      status: "Completed",
      position: "1st",
      date: "10th - 15th Sep. 2024",
      src: pubgTwo,
    },
    {
      id: 3,
      name: "Fortnite Battle Royale",
      game: "Fortnite",
      type: "Battle Royale",
      price: "N750,000",
      status: "In Progress",
      position: "2nd",
      date: "5th - 10th Sep. 2024",
      src: fortnite,
    },
    {
      id: 4,
      name: "Call of Duty Showdown",
      game: "Call of Duty",
      type: "Team Deathmatch",
      price: "N600,000",
      status: "Completed",
      position: "1st",
      date: "20th - 25th Aug. 2024",
      src: pubgThree,
    },
    {
      id: 5,
      name: "Valorant Clash",
      game: "Valorant",
      type: "Elimination",
      price: "N400,000",
      status: "Upcoming",
      position: "-",
      date: "12th - 16th Nov. 2024",
      src: fortnite,
    },
    {
      id: 6,
      name: "Rocket League World Cup",
      game: "Rocket League",
      type: "Knockout",
      price: "N850,000",
      status: "Completed",
      position: "3rd",
      date: "2nd - 7th Oct. 2024",
      src: pubg,
    },
    {
      id: 7,
      name: "League of Legends Masters",
      game: "League of Legends",
      type: "Double Elimination",
      price: "N1,200,000",
      status: "In Progress",
      position: "4th",
      date: "15th - 30th Sep. 2024",
      src: pubgTwo,
    },
    {
      id: 8,
      name: "Apex Legends Showdown",
      game: "Apex Legends",
      type: "Battle Royale",
      price: "N700,000",
      status: "Upcoming",
      position: "-",
      date: "25th - 29th Nov. 2024",
      src: pubgThree,
    },
    {
      id: 9,
      name: "Overwatch Championship",
      game: "Overwatch",
      type: "Elimination",
      price: "N900,000",
      status: "Completed",
      position: "2nd",
      date: "5th - 9th Aug. 2024",
      src: fortnite,
    },
    {
      id: 10,
      name: "Rainbow Six Siege Invitational",
      game: "Rainbow Six Siege",
      type: "Knockout",
      price: "N650,000",
      status: "In Progress",
      position: "3rd",
      date: "1st - 6th Oct. 2024",
      src: pubg,
    },
    {
      id: 11,
      name: "Dota 2 World Series",
      game: "Dota 2",
      type: "Elimination",
      price: "N1,500,000",
      status: "Upcoming",
      position: "-",
      date: "8th - 14th Dec. 2024",
      src: pubgTwo,
    },
    {
      id: 12,
      name: "CS:GO Champions Cup",
      game: "CS:GO",
      type: "Knockout",
      price: "N950,000",
      status: "Completed",
      position: "1st",
      date: "20th - 25th Sep. 2024",
      src: pubgThree,
    },
    {
      id: 13,
      name: "Smash Bros Ultimate",
      game: "Super Smash Bros",
      type: "Elimination",
      price: "N300,000",
      status: "Upcoming",
      position: "-",
      date: "5th - 10th Dec. 2024",
      src: fortnite,
    },
    {
      id: 14,
      name: "Hearthstone Global Finals",
      game: "Hearthstone",
      type: "Knockout",
      price: "N450,000",
      status: "In Progress",
      position: "5th",
      date: "10th - 15th Oct. 2024",
      src: pubg,
    },
    {
      id: 15,
      name: "Starcraft II Open",
      game: "Starcraft II",
      type: "Elimination",
      price: "N550,000",
      status: "Upcoming",
      position: "-",
      date: "1st - 7th Nov. 2024",
      src: pubgTwo,
    },
    {
    id: 16,
    name: "PUBG Tournament",
    game: "Counter Strike",
    type: "Elimination",
    price: "N500,000",
    status: "In Progress",
    position: "-",
    date: "1st - 21st Oct. 2024",
    src: pubg,
  },
  {
    id: 17,
    name: "FIFA 2024 Championship",
    game: "FIFA 2024",
    type: "Knockout",
    price: "N1,000,000",
    status: "Completed",
    position: "1st",
    date: "10th - 15th Sep. 2024",
    src: pubgTwo,
  },
  {
    id: 18,
    name: "Fortnite Battle Royale",
    game: "Fortnite",
    type: "Battle Royale",
    price: "N750,000",
    status: "In Progress",
    position: "2nd",
    date: "5th - 10th Sep. 2024",
    src: fortnite,
  },
  {
    id: 19,
    name: "Call of Duty Showdown",
    game: "Call of Duty",
    type: "Team Deathmatch",
    price: "N600,000",
    status: "Completed",
    position: "1st",
    date: "20th - 25th Aug. 2024",
    src: pubgThree,
  },
  {
    id: 20,
    name: "Valorant Clash",
    game: "Valorant",
    type: "Elimination",
    price: "N400,000",
    status: "Upcoming",
    position: "-",
    date: "12th - 16th Nov. 2024",
    src: fortnite,
  },
  {
    id: 21,
    name: "Rocket League World Cup",
    game: "Rocket League",
    type: "Knockout",
    price: "N850,000",
    status: "Completed",
    position: "3rd",
    date: "2nd - 7th Oct. 2024",
    src: pubg,
  },
  {
    id: 22,
    name: "League of Legends Masters",
    game: "League of Legends",
    type: "Double Elimination",
    price: "N1,200,000",
    status: "In Progress",
    position: "4th",
    date: "15th - 30th Sep. 2024",
    src: pubgTwo,
  },
  {
    id: 23,
    name: "Apex Legends Showdown",
    game: "Apex Legends",
    type: "Battle Royale",
    price: "N700,000",
    status: "Upcoming",
    position: "-",
    date: "25th - 29th Nov. 2024",
    src: pubgThree,
  },
  {
    id: 24,
    name: "Overwatch Championship",
    game: "Overwatch",
    type: "Elimination",
    price: "N900,000",
    status: "Completed",
    position: "2nd",
    date: "5th - 9th Aug. 2024",
    src: fortnite,
  },
  {
    id: 25,
    name: "Rainbow Six Siege Invitational",
    game: "Rainbow Six Siege",
    type: "Knockout",
    price: "N650,000",
    status: "In Progress",
    position: "3rd",
    date: "1st - 6th Oct. 2024",
    src: pubg,
  },
  {
    id: 26,
    name: "Dota 2 World Series",
    game: "Dota 2",
    type: "Elimination",
    price: "N1,500,000",
    status: "Upcoming",
    position: "-",
    date: "8th - 14th Dec. 2024",
    src: pubgTwo,
  },
  {
    id: 27,
    name: "CS:GO Champions Cup",
    game: "CS:GO",
    type: "Knockout",
    price: "N950,000",
    status: "Completed",
    position: "1st",
    date: "20th - 25th Sep. 2024",
    src: pubgThree,
  },
  {
    id: 28,
    name: "Smash Bros Ultimate",
    game: "Super Smash Bros",
    type: "Elimination",
    price: "N300,000",
    status: "Upcoming",
    position: "-",
    date: "5th - 10th Dec. 2024",
    src: fortnite,
  },
  {
    id: 29,
    name: "Hearthstone Global Finals",
    game: "Hearthstone",
    type: "Knockout",
    price: "N450,000",
    status: "In Progress",
    position: "5th",
    date: "10th - 15th Oct. 2024",
    src: pubg,
  },
  {
    id: 30,
    name: "Starcraft II Open",
    game: "Starcraft II",
    type: "Elimination",
    price: "N550,000",
    status: "Upcoming",
    position: "-",
    date: "1st - 7th Nov. 2024",
    src: pubgTwo,
  },
];
  