import pubg from "@/images/PUBG.jpg";
import pubgTwo from "@/images/PUBG_2.jpg";
import pubgThree from "@/images/PUBG_3.jpg";
import fortnite from "@/images/fortnite.jpg";

export const userEventsList = [
  {
    name: "PUBG Tournament",
    type: "Elimination",
    game: "Counter Strike",
    location: "Lagos, Nigeria",
    date: "1st - 21st Oct. 2024",
    status: "In Progress",
    src: pubg,
  },
  {
    name: "FIFA 2024 Championship",
    type: "Knockout",
    game: "FIFA 2024",
    location: "Abuja, Nigeria",
    date: "10th - 15th Sep. 2024",
    status: "Completed",
    src: pubgTwo,
  },
  {
    name: "Fortnite Battle Royale",
    type: "Battle Royale",
    game: "Fortnite",
    location: "Port Harcourt, Nigeria",
    date: "5th - 10th Sep. 2024",
    status: "In Progress",
    src: fortnite,
  },
  {
    name: "Call of Duty Showdown",
    type: "Team Deathmatch",
    game: "Call of Duty",
    location: "Lagos, Nigeria",
    date: "20th - 25th Aug. 2024",
    status: "Completed",
    src: pubgThree,
  },
  {
    name: "Valorant Clash",
    type: "Elimination",
    game: "Valorant",
    location: "Abuja, Nigeria",
    date: "12th - 16th Nov. 2024",
    status: "Upcoming",
    src: fortnite,
  },
  {
    name: "Rocket League World Cup",
    type: "Knockout",
    game: "Rocket League",
    location: "Port Harcourt, Nigeria",
    date: "2nd - 7th Oct. 2024",
    status: "Completed",
    src: pubg,
  },
  {
    name: "League of Legends Masters",
    type: "Double Elimination",
    game: "League of Legends",
    location: "Lagos, Nigeria",
    date: "15th - 30th Sep. 2024",
    status: "In Progress",
    src: pubgTwo,
  },
  {
    name: "Apex Legends Showdown",
    type: "Battle Royale",
    game: "Apex Legends",
    location: "Abuja, Nigeria",
    date: "25th - 29th Nov. 2024",
    status: "Upcoming",
    src: pubgThree,
  },
  {
    name: "Overwatch Championship",
    type: "Elimination",
    game: "Overwatch",
    location: "Port Harcourt, Nigeria",
    date: "5th - 9th Aug. 2024",
    status: "Completed",
    src: fortnite,
  },
  {
    name: "Rainbow Six Siege Invitational",
    type: "Knockout",
    game: "Rainbow Six Siege",
    location: "Lagos, Nigeria",
    date: "1st - 6th Oct. 2024",
    status: "In Progress",
    src: pubg,
  },
  {
    name: "Dota 2 World Series",
    type: "Elimination",
    game: "Dota 2",
    location: "Abuja, Nigeria",
    date: "8th - 14th Dec. 2024",
    status: "Upcoming",
    src: pubgTwo,
  },
  {
    name: "CS:GO Champions Cup",
    type: "Knockout",
    game: "CS:GO",
    location: "Port Harcourt, Nigeria",
    date: "20th - 25th Sep. 2024",
    status: "Completed",
    src: pubgThree,
  },
  {
    name: "Smash Bros Ultimate",
    type: "Elimination",
    game: "Super Smash Bros",
    location: "Lagos, Nigeria",
    date: "5th - 10th Dec. 2024",
    status: "Upcoming",
    src: fortnite,
  },
  {
    name: "Hearthstone Global Finals",
    type: "Knockout",
    game: "Hearthstone",
    location: "Abuja, Nigeria",
    date: "10th - 15th Oct. 2024",
    status: "In Progress",
    src: pubg,
  },
  {
    name: "Starcraft II Open",
    type: "Elimination",
    game: "Starcraft II",
    location: "Port Harcourt, Nigeria",
    date: "1st - 7th Nov. 2024",
    status: "Upcoming",
    src: pubgTwo,
  },
];
