import pubg from "@/images/PUBG.jpg";
import pubgTwo from "@/images/PUBG_2.jpg";
import pubgThree from "@/images/PUBG_3.jpg";
import fortnite from "@/images/fortnite.jpg";

export const participantsList = [
  {
    participant: "John Doe",
    type: "Individual",
    ranking: "#1",
    location: "Lagos, Nigeria",
    tournaments: 35,
    wins: 300000,
    losses: 5,
    src: pubg,
  },
  {
    participant: "Jane Smith",
    type: "Team",
    ranking: "#76",
    location: "Accra, Ghana",
    tournaments: 20,
    wins: 15,
    losses: 5,
    src: pubgTwo,
  },
  {
    participant: "Team Alpha",
    type: "Team",
    ranking: "#4",
    location: "Nairobi, Kenya",
    tournaments: 50,
    wins: 40,
    losses: 10,
    src: fortnite,
  },
  {
    participant: "Mike Johnson",
    type: "Individual",
    ranking: "#8",
    location: "Cape Town, South Africa",
    tournaments: 40,
    wins: 28,
    losses: 12,
    src: pubgThree,
  },
  {
    participant: "Team Bravo",
    type: "Team",
    ranking: "#25",
    location: "Cairo, Egypt",
    tournaments: 60,
    wins: 45,
    losses: 15,
    src: fortnite,
  },
  {
    participant: "Sarah Williams",
    type: "Individual",
    ranking: "#3",
    location: "Abuja, Nigeria",
    tournaments: 55,
    wins: 50,
    losses: 5,
    src: pubg,
  },
  {
    participant: "Team Delta",
    type: "Team",
    ranking: "#12",
    location: "Kampala, Uganda",
    tournaments: 25,
    wins: 18,
    losses: 7,
    src: pubgTwo,
  },
  {
    participant: "Emma Thompson",
    type: "Individual",
    ranking: "#22",
    location: "Dar es Salaam, Tanzania",
    tournaments: 33,
    wins: 20,
    losses: 13,
    src: pubgThree,
  },
  {
    participant: "Team Echo",
    type: "Team",
    ranking: "#16",
    location: "Accra, Ghana",
    tournaments: 45,
    wins: 30,
    losses: 15,
    src: fortnite,
  },
  {
    participant: "Alex Brown",
    type: "Individual",
    ranking: "#10",
    location: "Kigali, Rwanda",
    tournaments: 38,
    wins: 25,
    losses: 13,
    src: pubg,
  },
  {
    participant: "Team Gamma",
    type: "Team",
    ranking: "#14",
    location: "Johannesburg, South Africa",
    tournaments: 48,
    wins: 33,
    losses: 15,
    src: fortnite,
  },
  {
    participant: "Brian Taylor",
    type: "Individual",
    ranking: "#7",
    location: "Harare, Zimbabwe",
    tournaments: 29,
    wins: 20,
    losses: 9,
    src: pubgTwo,
  },
  {
    participant: "Team Zulu",
    type: "Team",
    ranking: "#6",
    location: "Lusaka, Zambia",
    tournaments: 60,
    wins: 55,
    losses: 5,
    src: pubgThree,
  },
  {
    participant: "Olivia Martin",
    type: "Individual",
    ranking: "#20",
    location: "Maputo, Mozambique",
    tournaments: 25,
    wins: 15,
    losses: 10,
    src: pubg,
  },
  {
    participant: "Team Omega",
    type: "Team",
    ranking: "#2",
    location: "Mombasa, Kenya",
    tournaments: 70,
    wins: 60,
    losses: 10,
    src: fortnite,
  },
  {
    participant: "Luke Adams",
    type: "Individual",
    ranking: "#50",
    location: "Windhoek, Namibia",
    tournaments: 18,
    wins: 10,
    losses: 8,
    src: pubgTwo,
  },
  {
    participant: "Team Theta",
    type: "Team",
    ranking: "#19",
    location: "Dodoma, Tanzania",
    tournaments: 42,
    wins: 32,
    losses: 10,
    src: pubgThree,
  },
  {
    participant: "Liam Nelson",
    type: "Individual",
    ranking: "#9",
    location: "Gaborone, Botswana",
    tournaments: 22,
    wins: 18,
    losses: 4,
    src: pubg,
  },
  {
    participant: "Team Sigma",
    type: "Team",
    ranking: "#5",
    location: "Freetown, Sierra Leone",
    tournaments: 65,
    wins: 55,
    losses: 10,
    src: fortnite,
  },
  {
    participant: "Sophia Johnson",
    type: "Individual",
    ranking: "#21",
    location: "Monrovia, Liberia",
    tournaments: 40,
    wins: 30,
    losses: 10,
    src: pubgTwo,
  },
  {
    participant: "Team Phoenix",
    type: "Team",
    ranking: "#11",
    location: "Conakry, Guinea",
    tournaments: 55,
    wins: 42,
    losses: 13,
    src: pubgThree,
  },
  {
    participant: "David Wright",
    type: "Individual",
    ranking: "#13",
    location: "Banjul, The Gambia",
    tournaments: 30,
    wins: 20,
    losses: 10,
    src: pubg,
  },
  {
    participant: "Team Crusaders",
    type: "Team",
    ranking: "#30",
    location: "Bamako, Mali",
    tournaments: 22,
    wins: 12,
    losses: 10,
    src: fortnite,
  },
  {
    participant: "Chloe Evans",
    type: "Individual",
    ranking: "#17",
    location: "Dakar, Senegal",
    tournaments: 48,
    wins: 33,
    losses: 15,
    src: pubgTwo,
  },
  {
    participant: "Team Warriors",
    type: "Team",
    ranking: "#23",
    location: "Ouagadougou, Burkina Faso",
    tournaments: 50,
    wins: 30,
    losses: 20,
    src: pubgThree,
  },
  {
    participant: "Mason Scott",
    type: "Individual",
    ranking: "#15",
    location: "Niamey, Niger",
    tournaments: 36,
    wins: 25,
    losses: 11,
    src: pubg,
  },
  {
    participant: "Team Legends",
    type: "Team",
    ranking: "#31",
    location: "Porto-Novo, Benin",
    tournaments: 58,
    wins: 35,
    losses: 23,
    src: fortnite,
  },
  {
    participant: "Grace Turner",
    type: "Individual",
    ranking: "#27",
    location: "Lome, Togo",
    tournaments: 41,
    wins: 28,
    losses: 13,
    src: pubgTwo,
  },
  {
    participant: "Lake Blade",
    type: "Individual",
    ranking: "#36",
    location: "Port Harcourt, Nigeria",
    tournaments: 401,
    wins: 45,
    losses: 10,
    src: fortnite,
  },
  {
    participant: "Team Avengers",
    type: "Team",
    ranking: "#9",
    location: "Abidjan, Côte d'Ivoire",
    tournaments: 37,
    wins: 27,
    losses: 10,
    src: pubgThree,
  },
  {
    participant: "Henry Davis",
    type: "Individual",
    ranking: "#6",
    location: "Libreville, Gabon",
    tournaments: 24,
    wins: 19,
    losses: 5,
    src: pubg,
  },
  {
    participant: "Team Spartans",
    type: "Team",
    ranking: "#28",
    location: "Kinshasa, DR Congo",
    tournaments: 29,
    wins: 22,
    losses: 7,
    src: fortnite,
  },
  {
    participant: "Ella White",
    type: "Individual",
    ranking: "#18",
    location: "Brazzaville, Congo",
    tournaments: 32,
    wins: 20,
    losses: 12,
    src: pubgTwo,
  },
  {
    participant: "Team Titans",
    type: "Team",
    ranking: "#24",
    location: "Luanda, Angola",
    tournaments: 66,
    wins: 45,
    losses: 21,
    src: pubgThree,
  },
  {
    participant: "James King",
    type: "Individual",
    ranking: "#32",
    location: "Yaoundé, Cameroon",
    tournaments: 45,
    wins: 25,
    losses: 20,
    src: pubg,
  },
  {
    participant: "Team Gamma",
    type: "Team",
    ranking: "#37",
    location: "Ilorin, Nigeria",
    tournaments: 45,
    wins: 15,
    losses: 10,
    src: pubg,
  },
  {
    participant: "Team Dragons",
    type: "Team",
    ranking: "#7",
    location: "Addis Ababa, Ethiopia",
    tournaments: 55,
    wins: 48,
    losses: 7,
    src: fortnite,
  }
];
