#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * Write key/en/fr/pt triples into all three dictionaries at once.
 *
 * Adding a string to `en` and forgetting `fr` and `pt` is silent: `t()` falls
 * back to the English and the page looks finished in every language. Doing it by
 * hand across three object literals in one 13,000-line file is how that gets
 * forgotten, so it is done by a script that reads the file back and counts.
 *
 * Usage: node scripts/write-strings.mjs <file.json> <label>
 *   file: { "some.key": ["English", "Français", "Português"], ... }
 *   label: a short name, used to mark the generated block so a second run
 *          replaces it rather than duplicating it.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DICT = path.join(HERE, '..', 'src', 'i18n', 'dictionaries.js');

const [file, label] = process.argv.slice(2);
if (!file || !label) {
  console.error('usage: node scripts/write-strings.mjs <file.json> <label>');
  process.exit(2);
}

const entries = Object.entries(JSON.parse(fs.readFileSync(file, 'utf8')));
for (const [key, values] of entries) {
  if (!Array.isArray(values) || values.length !== 3) {
    console.error(`${key}: needs exactly [English, French, Portuguese]`);
    process.exit(1);
  }
}

const lit = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const ANCHORS = [
  "    'help.whatYouCanDo': 'What you can do here',",
  "    'help.whatYouCanDo': 'Ce que vous pouvez y faire',",
  "    'help.whatYouCanDo': 'O que pode fazer aqui',",
];

const START = `    /* --- ${label}: generated by scripts/write-strings.mjs --- */\n`;
const END = `    /* --- end ${label} --- */\n`;

let text = fs.readFileSync(DICT, 'utf8');
while (text.includes(START)) {
  const from = text.indexOf(START);
  const to = text.indexOf(END, from) + END.length;
  text = text.slice(0, from) + text.slice(to);
}

for (let lang = 0; lang < 3; lang += 1) {
  const anchor = ANCHORS[lang];
  const at = text.indexOf(anchor);
  if (at === -1) throw new Error(`anchor not found for language ${lang}`);
  const block = START
    + entries.map(([key, v]) => `    ${lit(key)}: ${lit(v[lang])},`).join('\n')
    + '\n' + END;
  const insertAt = at + anchor.length + 1;
  text = text.slice(0, insertAt) + block + text.slice(insertAt);
}

fs.writeFileSync(DICT, text);

const written = fs.readFileSync(DICT, 'utf8');
let wrong = 0;
for (const [key] of entries) {
  const n = (written.match(new RegExp(`^ {4}'${key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}':`, 'gm')) || []).length;
  if (n !== 3) { wrong += 1; console.log(`  ${key} appears ${n} times`); }
}
if (wrong) { console.log(`${wrong} keys are not in all three`); process.exit(1); }
console.log(`${entries.length} strings written to en, fr and pt as "${label}"`);
