import pubg from "@/images/PUBG.jpg";
import pubgTwo from "@/images/PUBG_2.jpg";
import pubgThree from "@/images/PUBG_3.jpg";
import fortnite from "@/images/fortnite.jpg";

export const membersList = [
  {
    member: "John Doe",
    username: "@johndoe",
    role: "Captain",
    ranking: "#1",
    location: "Lagos, Nigeria",
    status: "Confirmed",
    src: pubg,
  },
  {
    member: "Jane Smith",
    username: "@janesmith",
    role: "Vice Captain",
    ranking: "#76",
    location: "Accra, Ghana",
    status: "Invite sent",
    src: pubgTwo,
  },
  {
    member: "Team Alpha",
    username: "@teamalpha",
    role: "Vice Captain",
    ranking: "#4",
    location: "Nairobi, Kenya",
    status: "Confirmed",
    src: fortnite,
  },
  {
    member: "Mike Johnson",
    username: "@mikejohnson",
    role: "Member",
    ranking: "#8",
    location: "Cape Town, South Africa",
    status: "Confirmed",
    src: pubgThree,
  },
  {
    member: "Team Bravo",
    username: "@teambravo",
    role: "Member",
    ranking: "#25",
    location: "Cairo, Egypt",
    status: "Confirmed",
    src: fortnite,
  },
  {
    member: "Sarah Williams",
    username: "@sarahwilliams",
    role: "Member",
    ranking: "#3",
    location: "Abuja, Nigeria",
    status: "Confirmed",
    src: pubg,
  },
  {
    member: "Team Delta",
    username: "@teamdelta",
    role: "Member",
    ranking: "#12",
    location: "Kampala, Uganda",
    status: "Invite sent",
    src: pubgTwo,
  },
  {
    member: "Emma Thompson",
    username: "@emmathompson",
    role: "Member",
    ranking: "#22",
    location: "Dar es Salaam, Tanzania",
    status: "Confirmed",
    src: pubgThree,
  },
  {
    member: "Team Echo",
    username: "@teamecho",
    role: "Member",
    ranking: "#16",
    location: "Accra, Ghana",
    status: "Confirmed",
    src: fortnite,
  },
  {
    member: "Alex Brown",
    username: "@alexbrown",
    role: "Member",
    ranking: "#10",
    location: "Kigali, Rwanda",
    status: "Confirmed",
    src: pubg,
  },
  {
    member: "Team Gamma",
    username: "@teamgamma",
    role: "Member",
    ranking: "#14",
    location: "Johannesburg, South Africa",
    status: "Confirmed",
    src: fortnite,
  },
  {
    member: "Brian Taylor",
    username: "@briantaylor",
    role: "Member",
    ranking: "#7",
    location: "Harare, Zimbabwe",
    status: "Invite sent",
    src: pubgTwo,
  },
  {
    member: "Team Zulu",
    username: "@teamzulu",
    role: "Member",
    ranking: "#6",
    location: "Lusaka, Zambia",
    status: "Confirmed",
    src: pubgThree,
  },
  {
    member: "Olivia Martin",
    username: "@oliviamartin",
    role: "Member",
    ranking: "#20",
    location: "Maputo, Mozambique",
    status: "Invite sent",
    src: pubg,
  },
  {
    member: "Team Omega",
    username: "@teamomega",
    role: "Member",
    ranking: "#2",
    location: "Mombasa, Kenya",
    status: "Confirmed",
    src: fortnite,
  },
  {
    member: "Luke Adams",
    username: "@lukeadams",
    role: "Member",
    ranking: "#50",
    location: "Windhoek, Namibia",
    status: "Invite sent",
    src: pubgTwo,
  },
  {
    member: "Team Theta",
    username: "@teamtheta",
    role: "Member",
    ranking: "#19",
    location: "Dodoma, Tanzania",
    status: "Confirmed",
    src: pubgThree,
  },
  {
    member: "Liam Nelson",
    username: "@liamnelson",
    role: "Member",
    ranking: "#9",
    location: "Gaborone, Botswana",
    status: "Invite sent",
    src: pubg,
  },
  {
    member: "Team Sigma",
    username: "@teamsigma",
    role: "Member",
    ranking: "#5",
    location: "Freetown, Sierra Leone",
    status: "Confirmed",
    src: fortnite,
  },
  {
    member: "Sophia Johnson",
    username: "@sophiajohnson",
    role: "Member",
    ranking: "#21",
    location: "Monrovia, Liberia",
    status: "Confirmed",
    src: pubgTwo,
  },
  {
    member: "Team Phoenix",
    username: "@teamphoenix",
    role: "Member",
    ranking: "#11",
    location: "Conakry, Guinea",
    status: "Confirmed",
    src: pubgThree,
  },
  {
    member: "David Wright",
    username: "@davidwright",
    role: "Member",
    ranking: "#13",
    location: "Banjul, The Gambia",
    status: "Invite sent",
    src: pubg,
  },
  {
    member: "Team Crusaders",
    username: "@teamcrusaders",
    role: "Member",
    ranking: "#30",
    location: "Bamako, Mali",
    status: "Invite sent",
    src: fortnite,
  },
  {
    member: "Chloe Evans",
    username: "@chloeevans",
    role: "Member",
    ranking: "#17",
    location: "Dakar, Senegal",
    status: "Confirmed",
    src: pubgTwo,
  },
  {
    member: "Team Warriors",
    username: "@teamwarriors",
    role: "Member",
    ranking: "#23",
    location: "Ouagadougou, Burkina Faso",
    status: "Confirmed",
    src: pubgThree,
  },
  {
    member: "Mason Scott",
    username: "@masonscott",
    role: "Member",
    ranking: "#15",
    location: "Niamey, Niger",
    status: "Confirmed",
    src: pubg,
  },
  {
    member: "Team Legends",
    username: "@teamlegends",
    role: "Member",
    ranking: "#31",
    location: "Porto-Novo, Benin",
    status: "Confirmed",
    src: fortnite,
  },
  {
    member: "Grace Turner",
    username: "@graceturner",
    role: "Member",
    ranking: "#27",
    location: "Lome, Togo",
    status: "Confirmed",
    src: pubgTwo,
  },
  {
    member: "Lake Blade",
    username: "@lakeblade",
    role: "Member",
    ranking: "#36",
    location: "Port Harcourt, Nigeria",
    status: "Confirmed",
    src: fortnite,
  },
  {
    member: "Team Avengers",
    username: "@teamavengers",
    role: "Member",
    ranking: "#9",
    location: "Abidjan, Côte d'Ivoire",
    status: "Confirmed",
    src: pubgThree,
  },
  {
    member: "Henry Davis",
    username: "@henrydavis",
    role: "Member",
    ranking: "#6",
    location: "Libreville, Gabon",
    status: "Invite sent",
    src: pubg,
  },
  {
    member: "Team Spartans",
    username: "@teamspartans",
    role: "Member",
    ranking: "#28",
    location: "Kinshasa, DR Congo",
    status: "Invite sent",
    src: fortnite,
  },
  {
    member: "Ella White",
    username: "@ellawhite",
    role: "Member",
    ranking: "#18",
    location: "Brazzaville, Congo",
    status: "Confirmed",
    src: pubgTwo,
  },
  {
    member: "Team Titans",
    username: "@teamtitans",
    role: "Member",
    ranking: "#24",
    location: "Luanda, Angola",
    status: "Confirmed",
    src: pubgThree,
  },
  {
    member: "James King",
    username: "@jamesking",
    role: "Member",
    ranking: "#32",
    location: "Yaoundé, Cameroon",
    status: "Confirmed",
    src: pubg,
  },
  {
    member: "Team Gamma",
    username: "@teamgamma",
    role: "Member",
    ranking: "#37",
    location: "Ilorin, Nigeria",
    status: "Confirmed",
    src: pubg,
  },
  {
    member: "Team Dragons",
    username: "@teamdragons",
    role: "Member",
    ranking: "#7",
    location: "Addis Ababa, Ethiopia",
    status: "Confirmed",
    src: fortnite,
  }
];
